<?php

namespace Database\Seeders;

use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use App\Models\UserData;
use Illuminate\Support\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use App\Models\AttendanceLog;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $this->call([
            RolesAndPermissionsSeeder::class,
            BadgeSeeder::class,
        ]);
        // $this->middleware('permission:manage users');
        // $this->middleware('role:SUPER ADMIN'); // etc.


        // User::factory(10)->create();

        // User::factory()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);
        //i want you to remove the manager, and change department to department_id , assign the values of department as follows, Design = 0, Development = 1, Marketing = 2, Office Manangement = 3
        $departments = [
            [
                'name' => 'Design',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Development',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Marketing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Office Management',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach (array_chunk($departments, 50) as $chunk) {
            DB::table('departments')->insert($chunk);
        }
        
        $users = [
            [
                'display_name' => 'John Pet',
                'name' => 'John Petalcurin',
                'first_name' => 'John Ernesto',
                'last_name' => 'Petalcurin',
                'middle_name' => '',
                'suffix_name' => '',
                'sex' => \App\Enum\Sex::MALE,
                'photo' => 'avatar/jp.jpg',
                'email' => 'jp@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'inactive',
                'active' => 0,
                'bio_metric_id' => '3',
                'department_id' => 0,
                'job_title' => 'Design',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
                'birthday' => '1985-05-15',
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Gee',
                'name' => 'Gee Actub',
                'first_name' => 'Gee',
                'last_name' => 'Actub',
                'middle_name' => '',
                'suffix_name' => '',
                'photo' => 'avatar/gee.jpg',
                'sex' => \App\Enum\Sex::MALE,
                'email' => 'gee@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'active',
                'active' => '1',
                'bio_metric_id' => '5',
                'department_id' => 1,
                'job_title' => 'Development',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Nik',
                'name' => 'Nik Cyrell Z. Yabo',
                'first_name' => 'Nik Cyrell',
                'last_name' => 'Yabo',
                'middle_name' => 'Z',
                'suffix_name' => '',
                'photo' => 'avatar/nik.jpg',
                'sex' => \App\Enum\Sex::MALE,
                'email' => 'nik@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'active',
                'active' => '1',
                'bio_metric_id' => '6',
                'department_id' => 0,
                'job_title' => 'Design',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Vevien',
                'name' => 'Vevien Consolacion',
                'first_name' => 'Vevien',
                'last_name' => 'Consolacion',
                'middle_name' => '',
                'suffix_name' => '',
                'photo' => 'avatar/vevien.jpg',
                'sex' => \App\Enum\Sex::FEMALE,
                'email' => 'vevien@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'active',
                'active' => 1,
                'bio_metric_id' => 7,
                'department_id' => 2,
                'job_title' => 'Marketing',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Jefel',
                'name' => 'Jefel Prayles',
                'first_name' => 'Jefel',
                'last_name' => 'Prayles',
                'middle_name' => '',
                'suffix_name' => '',
                'photo' => 'avatar/jefel.jpg',
                'sex' => \App\Enum\Sex::FEMALE,
                'email' => 'jefel@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'active',
                'active' => 1,
                'bio_metric_id' => 8,
                'department_id' => 0,
                'job_title' => 'Design',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Jonathan',
                'name' => 'Jonathan Macas',
                'first_name' => 'Jonathan',
                'last_name' => 'Macas',
                'middle_name' => '',
                'suffix_name' => '',
                'sex' => \App\Enum\Sex::MALE,
                'photo' => 'avatar/jonathan.jpg',
                'email' => 'jonathan@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'inactive',
                'active' => 0,
                'bio_metric_id' => 9,
                'department_id' => 3,
                'job_title' => 'PH Office Management',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Ariel',
                'name' => 'Ariel Acha',
                'first_name' => 'Ariel',
                'last_name' => 'Acha',
                'middle_name' => 'B',
                'suffix_name' => '',
                'photo' => 'avatar/ariel.jpg',
                'sex' => \App\Enum\Sex::MALE,
                'email' => 'ariel@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'inactive',
                'active' => 0,
                'bio_metric_id' => 10,
                'department_id' => 1,
                'job_title' => 'Development',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Nico',
                'name' => 'Nico Sendaydiego',
                'first_name' => 'Nico',
                'last_name' => 'Sendaydiego',
                'middle_name' => '',
                'suffix_name' => '',
                'photo' => 'avatar/nico.jpg',
                'sex' => \App\Enum\Sex::MALE,
                'email' => 'nico@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'inactive',
                'active' => 0,
                'bio_metric_id' => 11,
                'department_id' => 3,
                'job_title' => 'PH Office Management',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Roy',
                'name' => 'Roy',
                'first_name' => 'Roy Kevin',
                'last_name' => 'Hormillada',
                'middle_name' => '',
                'suffix_name' => '',
                'sex' => \App\Enum\Sex::MALE,
                'photo' => 'avatar/roy.jpg',
                'email' => 'roy@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'inactive',
                'active' => 1,
                'bio_metric_id' => 12,
                'department_id' => 1,
                'job_title' => 'Project Management/QA',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Danilo',
                'name' => 'Danilo A. Ortega Jr.',
                'first_name' => 'Danilo',
                'last_name' => 'Ortega',
                'middle_name' => 'A',
                'suffix_name' => 'Jr',
                'sex' => \App\Enum\Sex::MALE,
                'photo' => 'avatar/dan.jpg',
                'email' => 'dan@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'active',
                'active' => 1,
                'bio_metric_id' => 13,
                'department_id' => 3,
                'job_title' => 'PH Office Management / Scatterist',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Christian',
                'name' => 'Christian',
                'first_name' => 'Christian',
                'last_name' => 'Baloncio',
                'middle_name' => '',
                'suffix_name' => '',
                'sex' => \App\Enum\Sex::MALE,
                'email' => 'christian@digitalfeet.com',
                'password' => Hash::make('password'),
                'photo' => 'avatar/christian.jpg',
                'status' => 'active',
                'active' => 1,
                'bio_metric_id' => 14,
                'department_id' => 1,
                'job_title' => 'Marketing Automation Expert / HubSpot Expert / WordPress Specialist / Senior Full-Stack Developer / Most Panctual',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Flore',
                'name' => 'Flore',
                'first_name' => 'Flore',
                'last_name' => 'Virtudazo',
                'middle_name' => '',
                'suffix_name' => '',
                'sex' => \App\Enum\Sex::FEMALE,
                'email' => 'flore@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'active',
                'active' => 1,
                'bio_metric_id' => 15,
                'photo' => 'avatar/flore.jpg',
                'department_id' => 2,
                'job_title' => 'Marketing',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Marc Jason',
                'name' => 'Jason',
                'first_name' => 'Marc Jason',
                'last_name' => 'Dado',
                'middle_name' => '',
                'suffix_name' => '',
                'photo' => 'avatar/jason.jpg',
                'sex' => \App\Enum\Sex::MALE,
                'email' => 'jason@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'active',
                'active' => 1,
                'bio_metric_id' => 16,
                'department_id' => 1,
                'job_title' => 'WordPress Expert / Technical SEO Expert / Senior Full-Stack Developer',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Kent',
                'name' => 'Kent',
                'first_name' => 'Kent',
                'last_name' => '',
                'middle_name' => '',
                'suffix_name' => '',
                'sex' => \App\Enum\Sex::MALE,
                'email' => 'kent@digitalfeet.com',
                'password' => Hash::make('password'),
                'photo' => 'avatar/kent.jpg',
                'status' => 'inactive',
                'active' => 0,
                'bio_metric_id' => 17,
                'department_id' => 0,
                'job_title' => 'Project Management/QA',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Anna',
                'name' => 'Anna',
                'first_name' => 'Anna Rose',
                'last_name' => '',
                'middle_name' => '',
                'suffix_name' => '',
                'sex' => \App\Enum\Sex::FEMALE,
                'email' => 'anna@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'inactive',
                'active' => 0,
                'photo' => 'avatar/anna.jpg',
                'bio_metric_id' => 18,
                'department_id' => 2,
                'job_title' => 'Marketing',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Vernan',
                'name' => 'Vernan Laguican',
                'first_name' => 'Vernan',
                'last_name' => 'Laguican',
                'middle_name' => '',
                'suffix_name' => '',
                'sex' => \App\Enum\Sex::MALE,
                'email' => 'vernan@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'inactive',
                'active' => 1,
                'bio_metric_id' => 19,
                'photo' => 'avatar/vernan.jpg',
                'department_id' => 2,
                'job_title' => 'Marketing',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Hanniel',
                'name' => 'Hanniel Grace Estareja',
                'first_name' => 'Hanniel Grace',
                'last_name' => 'Estareja',
                'middle_name' => '',
                'suffix_name' => '',
                'sex' => \App\Enum\Sex::FEMALE,
                'email' => 'hanniel@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'active',
                'active' => 1,
                'bio_metric_id' => 20,
                'photo' => 'avatar/hanniel.jpg',
                'department_id' => 3,
                'job_title' => 'Project Management/QA',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Leah',
                'name' => 'Leah Rosephil Lambunao',
                'first_name' => 'Leah Rosephil',
                'last_name' => 'Lambunao',
                'middle_name' => '',
                'suffix_name' => '',
                'sex' => \App\Enum\Sex::FEMALE,
                'email' => 'leah@digitalfeet.com',
                'password' => Hash::make('password'),
                'photo' => 'avatar/leah.jpg',
                'status' => 'inactive',
                'active' => 0,
                'bio_metric_id' => 21,
                'department_id' => 3,
                'job_title' => 'Project Management/QA',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Clyde',
                'name' => 'Clyde Escolano',
                'first_name' => 'Clyde',
                'last_name' => 'Escolano',
                'middle_name' => 'E',
                'suffix_name' => '',
                'photo' => 'avatar/clyde.jpg',
                'sex' => \App\Enum\Sex::MALE,
                'email' => 'clyde@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'active',
                'active' => 0,
                'bio_metric_id' => 22,
                'department_id' => 2,
                'job_title' => 'Marketing',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Renzo',
                'name' => 'Renzo Miguel',
                'first_name' => 'Renzo Miguel',
                'last_name' => 'Martil',
                'middle_name' => '',
                'suffix_name' => '',
                'sex' => \App\Enum\Sex::MALE,
                'email' => 'renzo@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'active',
                'photo' => 'avatar/renzo.jpg',
                'active' => 1,
                'bio_metric_id' => 24,
                'department_id' => 0,
                'job_title' => 'Design',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Jane',
                'name' => 'Jane Aguilos',
                'first_name' => 'Regina Jane',
                'last_name' => 'Aguilos',
                'middle_name' => '',
                'suffix_name' => '',
                'sex' => \App\Enum\Sex::FEMALE,
                'email' => 'jane@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'inactive',
                'photo' => 'avatar/jane.jpg',
                'active' => 0,
                'bio_metric_id' => 24,
                'department_id' => 1,
                'job_title' => 'Development',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Cez',
                'name' => 'Cez Nicole Bazar',
                'first_name' => 'Cez Nicole',
                'last_name' => 'Bazar',
                'middle_name' => '',
                'suffix_name' => '',
                'sex' => \App\Enum\Sex::FEMALE,
                'email' => 'cez@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'inactive',
                'active' => 1,
                'bio_metric_id' => 27,
                'photo' => 'avatar/cez.jpg',
                'department_id' => 3,
                'job_title' => 'Project Management/QA',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Judd',
                'name' => 'Judd Riaghan A. Vallente',
                'first_name' => 'Judd Riaghan',
                'last_name' => 'Vallente',
                'middle_name' => 'A',
                'suffix_name' => '',
                'photo' => 'avatar/judd.jpg',
                'sex' => \App\Enum\Sex::MALE,
                'email' => 'judd@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'inactive',
                'active' => 0,
                'bio_metric_id' => 28,
                'department_id' => 1,
                'job_title' => 'Development',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Guile',
                'name' => 'Guile Canencia',
                'first_name' => 'Guile',
                'last_name' => 'Canencia',
                'middle_name' => '',
                'suffix_name' => '',
                'sex' => \App\Enum\Sex::MALE,
                'email' => 'guile@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'inactive',
                'active' => 0,
                'photo' => 'avatar/guile.jpg',
                'bio_metric_id' => 29,
                'department_id' => 2,
                'job_title' => 'Marketing',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Engel',
                'name' => 'Engelbert Bahia',
                'first_name' => 'Engelbert',
                'last_name' => 'Bahia',
                'middle_name' => '',
                'suffix_name' => '',
                'sex' => \App\Enum\Sex::MALE,
                'email' => 'engel@digitalfeet.com',
                'password' => Hash::make('password'),
                'photo' => 'avatar/engel.jpg',
                'status' => 'active',
                'active' => 1,
                'bio_metric_id' => 30,
                'department_id' => 2,
                'job_title' => 'Marketing',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Kassie',
                'name' => 'Kassandra Erika Sobiono',
                'first_name' => 'Kassandra Erika',
                'last_name' => 'Sobiono',
                'middle_name' => '',
                'suffix_name' => '',
                'sex' => \App\Enum\Sex::FEMALE,
                'email' => 'kassandra@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'inactive',
                'active' => 0,
                'photo' => 'avatar/kassandra.jpg',
                'bio_metric_id' => 31,
                'department_id' => 3,
                'job_title' => 'Project Management/QA',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Fred',
                'name' => 'Godofredo Gundaya Ledesma II',
                'first_name' => 'Godofredo Gundaya',
                'last_name' => 'Ledesma',
                'middle_name' => '',
                'suffix_name' => '2nd',
                'photo' => 'avatar/fred.jpg',
                'sex' => \App\Enum\Sex::MALE,
                'email' => 'fred@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'active',
                'active' => 1,
                'bio_metric_id' => 32,
                'department_id' => 0,
                'job_title' => 'Design',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Ela',
                'name' => 'Phamela Baculio',
                'first_name' => 'Phamela',
                'last_name' => 'Baculio',
                'middle_name' => '',
                'suffix_name' => '',
                'photo' => 'avatar/phamela.jpg',
                'sex' => \App\Enum\Sex::FEMALE,
                'email' => 'phamela@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'active',
                'active' => 1,
                'bio_metric_id' => 33,
                'department_id' => 3,
                'job_title' => 'PH Office Management',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Leila',
                'name' => 'Khaleila Bitas',
                'first_name' => 'Khaleila',
                'last_name' => 'Bitas',
                'middle_name' => '',
                'suffix_name' => '',
                'sex' => \App\Enum\Sex::FEMALE,
                'photo' => 'avatar/leila.jpg',
                'email' => 'leila@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'active',
                'active' => 1,
                'bio_metric_id' => 34,
                'department_id' => 2,
                'job_title' => 'Marketing',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'John',
                'name' => 'John Louie Baranggan',
                'first_name' => 'John Louie',
                'last_name' => 'Barangan',
                'middle_name' => '',
                'suffix_name' => '',
                'sex' => \App\Enum\Sex::MALE,
                'email' => 'louie@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'active',
                'photo' => 'avatar/louie.jpg',
                'active' => 1,
                'bio_metric_id' => 35,
                'department_id' => 1,
                'job_title' => 'Team Leader Development Team',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Romeo',
                'name' => 'Romeo Nombre Jr.',
                'first_name' => 'Romeo',
                'last_name' => 'Nombre',
                'middle_name' => '',
                'suffix_name' => 'Jr',
                'photo' => 'avatar/romeo.jpg',
                'sex' => \App\Enum\Sex::MALE,
                'email' => 'romeo@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'active',
                'active' => 1,
                'bio_metric_id' => 36,
                'department_id' => 1,
                'job_title' => 'Technical SEO Specialist',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'John D',
                'name' => 'John Dexter M. Gamo',
                'first_name' => 'John Dexter',
                'last_name' => 'Gamo',
                'middle_name' => 'M',
                'suffix_name' => '',
                'photo' => 'avatar/dexter.jpg',
                'sex' => \App\Enum\Sex::MALE,
                'email' => 'dexter@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'active',
                'active' => 1,
                'bio_metric_id' => 37,
                'department_id' => 0,
                'job_title' => 'Design',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Ken',
                'name' => 'Ken Vincent F. Jemenia',
                'first_name' => 'Ken Vincent',
                'last_name' => 'Jemenia',
                'middle_name' => 'F',
                'suffix_name' => '',
                'photo' => 'avatar/ken.jpg',
                'sex' => \App\Enum\Sex::MALE,
                'email' => 'ken@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'inactive',
                'active' => 0,
                'bio_metric_id' => 38,
                'department_id' => 0,
                'job_title' => 'Design',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Glen',
                'name' => 'Glen Mark Olivar',
                'first_name' => 'Glen Mark',
                'last_name' => 'Olivar',
                'middle_name' => '',
                'suffix_name' => '',
                'sex' => \App\Enum\Sex::MALE,
                'email' => 'glen@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'active',
                'photo' => 'avatar/glen.jpg',
                'active' => 1,
                'bio_metric_id' => 39,
                'department_id' => 1,
                'job_title' => 'Development',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'James',
                'name' => 'James Dei F. Panganiban',
                'first_name' => 'James Dei',
                'last_name' => 'Panganiban',
                'middle_name' => 'F',
                'suffix_name' => '',
                'sex' => \App\Enum\Sex::MALE,
                'email' => 'james@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'active',
                'photo' => 'avatar/james.jpg',
                'active' => 1,
                'bio_metric_id' => 40,
                'department_id' => 3,
                'job_title' => 'Project Management/QA',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'John-Rey',
                'name' => 'John-Rey C. Jamago',
                'first_name' => 'John-Rey',
                'last_name' => 'Jamago',
                'middle_name' => 'C',
                'suffix_name' => '',
                'photo' => 'avatar/johnrey.jpg',
                'sex' => \App\Enum\Sex::MALE,
                'email' => 'johnrey@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'active',
                'active' => 1,
                'bio_metric_id' => '41',
                'department_id' => 1,
                'job_title' => 'Development',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ],
            [
                'display_name' => 'Jaya',
                'name' => 'Jaya Estanilla',
                'first_name' => 'Jaya',
                'last_name' => 'Estanilla',
                'middle_name' => '',
                'suffix_name' => '',
                'sex' => \App\Enum\Sex::FEMALE,
                'email' => 'jaya@digitalfeet.com',
                'password' => Hash::make('password'),
                'status' => 'inactive',
                'active' => '0',
                'photo' => 'avatar/jaya.jpg',
                'bio_metric_id' => '41',
                'department_id' => 2,
                'job_title' => 'Marketing',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
                'birthday' => now()->subYears(rand(18, 60))->format('Y-m-d'),
                'phone' => '+63'.rand(100000000, 999999999),
            ]
        ];

        // The user rows above use a legacy 0-based department index. The
        // departments table (inserted above) is 1-based, so shift each into a
        // valid foreign key (Design=1 ... Office Management=4) before inserting.
        foreach ($users as &$user) {
            if (isset($user['department_id'])) {
                $user['department_id'] = $user['department_id'] + 1;
            }
        }
        unset($user);

        // Insert users in chunks to avoid memory issues with large datasets
        foreach (array_chunk($users, 50) as $chunk) {
            DB::table('users')->insert($chunk);
        }

        $startDate = Carbon::now()->subDays(50);

        for($i = 1; $i <= 36; $i++){
            
            UserData::create([
                'user_id' => $i,
                'vacation_leave' => 10,
                'sick_leave' => 10,
                'emergency_leave' => 10,
                'bereavement_leave' => 10,
                'maternity_leave' => 90,
                'paternity_leave' => 10,
                'time_in' => '10:00',
                'time_out' => '18:00',
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            for ($x = 0; $x < 50; $x++) {
                $date = $startDate->copy()->addDays($x);
            
                // Clock-in record
                AttendanceLog::create([
                    'user_id' => $i,
                    'type' => 'clockin',
                    'device' => 'web',
                    'remarks' => 'User clocked in',
                    'created_at' => $date->copy()->setHour(9)->setMinute(0)->setSecond(0), // 9:00 AM
                    'updated_at' => $date->copy()->setHour(9)->setMinute(0)->setSecond(0),
                ]);
            
                // Clock-out record
                AttendanceLog::create([
                    'user_id' => $i,
                    'type' => 'clockout',
                    'device' => 'web',
                    'remarks' => 'User clocked out',
                    'created_at' => $date->copy()->setHour(18)->setMinute(0)->setSecond(0), // 6:00 PM
                    'updated_at' => $date->copy()->setHour(18)->setMinute(0)->setSecond(0),
                ]);
            }

            $user_a = User::find(2);
            $user_a->assignRole('superadmin');
            $user_a->assignRole('super_admin');

            $user_b = User::find(4);
            $user_b->assignRole('teamleader');

            $user_c = User::find(30);
            $user_c->assignRole('teamleader');

            $user_d = User::find(25);
            $user_d->assignRole('teamleader');
        }
    }
}
